### ISSUE TITLE
Mismatch in prop names

### ISSUE THREAD

**Issue by moltar** [berenddeboer/cdk-rds-sql#8]
This should be `Database`:

https://github.com/berenddeboer/cdk-rds-sql/blob/2ee7dd1e969bb7b0d7291faa0d6b66f49c34498b/src/role.custom-resource.ts#L58

As that is what the handler expects:

https://github.com/berenddeboer/cdk-rds-sql/blob/2ee7dd1e969bb7b0d7291faa0d6b66f49c34498b/src/handler.ts#L214

Otherwise, an error is thrown:

```json
{
    "errorType": "error",
    "errorMessage": "database \"root\" does not exist",
    "code": "3D000",
    "length": 89,
    "name": "error",
    "severity": "FATAL",
    "file": "postinit.c",
    "line": "921",
    "routine": "InitPostgres",
    "stack": [
        "error: database \"root\" does not exist",
        "    at Parser.parseErrorMessage (/var/task/index.js:22772:98)",
        "    at Parser.handlePacket (/var/task/index.js:22613:25)",
        "    at Parser.parse (/var/task/index.js:22537:34)",
        "    at Socket.<anonymous> (/var/task/index.js:22813:44)",
        "    at Socket.emit (node:events:513:28)",
        "    at addChunk (node:internal/streams/readable:315:12)",
        "    at readableAddChunk (node:internal/streams/readable:289:9)",
        "    at Socket.Readable.push (node:internal/streams/readable:228:10)",
        "    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
    ]
}
```

**Comment by berenddeboer** [comment]
I think this is fixed now.
